In [1]:
print('hello coursEra grader! Please be kind!')

hello coursEra grader! Please be kind!

# My Work

In [18]:
import pandas as pd
import sqlite3
from sqlite3 import Error
import csv

# This is how I created a database
def create_connection(db_file):
    """ create a database connection to a SQLite database """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
    finally:
        if conn:
            conn.close()
            
if __name__ == '__main__':
    create_connection(r"C:\sqlite3\db_coursera\sqlite.db")

In [3]:
database = r"C:\sqlite3\db_coursera\sqlite.db"
create_table_sql_1 = """

CREATE TABLE IF NOT EXISTS ChicagoCensusData (
	id COMMUNITY_AREA_NUMBER PRIMARY KEY,
	COMMUNITY_AREA_NAME text,
	PERCENT_OF_HOUSING_CROWDED real,
	PERCENT_HOUSEHOLDS_BELOW_POVERTY real,
    PERCENT_AGED_16__UNEMPLOYED real,
    PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA real,
    PERCENT_AGED_UNDER_18_OR_OVER_64 real,
    PER_CAPITA_INCOME real,
    HARDSHIP_INDEX integer
);"""
        
create_table_sql_2 = """
CREATE TABLE IF NOT EXISTS ChicagoCrimeData (
	id COMMUNITY_AREA_NUMBER PRIMARY KEY,
	ID integer,
	CASE_NUMBER text,
	DATE text,
	BLOCK text,
	IUCR text,
	DESCRIPTION text,
    LOCATION_DESCRIPTION text,
    ARREST text,
    DOMESTIC text,
    BEAT integer,
    DISTRICT integer,
    WARD integer,
    FBICODE text,
    X_COORDINATE integer,
    Y_COORDINATE integer,
    YEAR integer,
    LATITUDE real,
    LONGITUDE real,
    LOCATION text
);"""

create_table_sql_3 = """
CREATE TABLE IF NOT EXISTS ChicagoPublicSchools (
	id COMMUNITY_AREA_NUMBER PRIMARY KEY,
	School_ID integer,
	NAME_OF_SCHOOL text,
	"Elementary, Middle, or High School" text,
	Street_Address text,
	City text,
	State text,
    ZIP_Code integer,
    Phone_Number text,
    Link text,
    Network_Manager text,
    Collaborative_Name text,
    Adequate_Yearly_Progress_Made_ text,
    Track_Schedule text,
    CPS_Performance_Policy_Status text,
    CPS_Performance_Policy_Level text,
    HEALTHY_SCHOOL_CERTIFIED text,
    Safety_Icon text,
    SAFETY_SCORE text,
    Family_Involvement_Icon text,
    Family_Involvement_Score text,
    Environment_Icon text,
    Environment_Score integer,
    Instruction_Icon text,
    Instruction_Score text,
    Leaders_Icon text,
    Leaders_Score text,
    Teachers_Icon text,
    Teachers_Score text,
    Parent_Engagement_Icon text,
    Parent_Engagement_Score text,
    Parent_Environment_Icon text,
    Parent_Environment_Score text,
    AVERAGE_STUDENT_ATTENDANCE text,
    Rate_of_Misconducts__per_100_students_ real,
    Average_Teacher_Attendance text,
    Individualized_Education_Program_Compliance_Rate text,
    Pk_2_Literacy__ text,
    Pk_2_Math__ text,
    Gr3_5_Grade_Level_Math__ text,
    Gr3_5_Grade_Level_Read__ text,
    Gr3_5_Keep_Pace_Read__ text,
    Gr3_5_Keep_Pace_Math__ text,
    Gr6_8_Grade_Level_Math__ text,
    Gr6_8_Grade_Level_Read__ text,
    Gr6_8_Keep_Pace_Math_ text,
    Gr6_8_Keep_Pace_Read__ text,
    Gr_8_Explore_Math__ text,
    Gr_8_Explore_Read__ text,
    ISAT_Exceeding_Math__ real,
    ISAT_Exceeding_Reading__ real,
    ISAT_Value_Add_Math real,
    ISAT_Value_Add_Read real,
    ISAT_Value_Add_Color_Math text,
    ISAT_Value_Add_Color_Read text,
    Students_Taking__Algebra__ text,
    Students_Passing__Algebra__ text,
    "9th Grade EXPLORE (2009)" text,
    "9th Grade EXPLORE (2010)" text,
    "10th Grade PLAN (2009)" text,
    "10th Grade PLAN (2010)" text,
    Net_Change_EXPLORE_and_PLAN text,
    "11th Grade Average ACT (2011)" text,
    Net_Change_PLAN_and_ACT text,
    College_Eligibility__ text,
    Graduation_Rate__ text,
    College_Enrollment_Rate__ text,
    COLLEGE_ENROLLMENT integer,
    General_Services_Route integer,
    Freshman_on_Track_Rate__ text,
    X_COORDINATE integer,
    Y_COORDINATE integer,
    Latitude real,
    Longitude real,
    COMMUNITY_AREA_NAME text, 
    Ward integer,
    Police_District	integer,
    Location text
);"""

In [9]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        return conn
    except Error as e:
        print(e)

    return conn

In [10]:
def create_table(conn, create_table_sql):
    """ create a table from the create_table_sql statement
    :param conn: Connection object
    :param create_table_sql: a CREATE TABLE statement
    :return:
    """
    try:
        c = conn.cursor()
        c.execute(create_table_sql)
    except Error as e:
        print(e)

In [11]:
def main():

    database = r"C:\sqlite3\db_coursera\sqlite.db"
    # create a database connection
    conn = create_connection(database)


create_table_sql_1 = """

CREATE TABLE IF NOT EXISTS ChicagoCensusData (
	id COMMUNITY_AREA_NUMBER PRIMARY KEY,
	COMMUNITY_AREA_NAME text,
	PERCENT_OF_HOUSING_CROWDED real,
	PERCENT_HOUSEHOLDS_BELOW_POVERTY real,
    PERCENT_AGED_16__UNEMPLOYED real,
    PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA real,
    PERCENT_AGED_UNDER_18_OR_OVER_64 real,
    PER_CAPITA_INCOME real,
    HARDSHIP_INDEX integer
);"""
        
create_table_sql_2 = """
CREATE TABLE IF NOT EXISTS ChicagoCrimeData (
	id COMMUNITY_AREA_NUMBER PRIMARY KEY,
	ID integer,
	CASE_NUMBER text,
	DATE text,
	BLOCK text,
	IUCR text,
    PRIMARY_TYPE text,
	DESCRIPTION text,
    LOCATION_DESCRIPTION text,
    ARREST text,
    DOMESTIC text,
    BEAT integer,
    DISTRICT integer,
    WARD integer,
    FBICODE text,
    X_COORDINATE integer,
    Y_COORDINATE integer,
    YEAR integer,
    LATITUDE real,
    LONGITUDE real,
    LOCATION text
);"""

create_table_sql_3 = """
CREATE TABLE IF NOT EXISTS ChicagoPublicSchools (
	id COMMUNITY_AREA_NUMBER PRIMARY KEY,
	School_ID integer,
	NAME_OF_SCHOOL text,
	"Elementary, Middle, or High School" text,
	Street_Address text,
	City text,
	State text,
    ZIP_Code integer,
    Phone_Number text,
    Link text,
    Network_Manager text,
    Collaborative_Name text,
    Adequate_Yearly_Progress_Made_ text,
    Track_Schedule text,
    CPS_Performance_Policy_Status text,
    CPS_Performance_Policy_Level text,
    HEALTHY_SCHOOL_CERTIFIED text,
    Safety_Icon text,
    SAFETY_SCORE text,
    Family_Involvement_Icon text,
    Family_Involvement_Score text,
    Environment_Icon text,
    Environment_Score integer,
    Instruction_Icon text,
    Instruction_Score text,
    Leaders_Icon text,
    Leaders_Score text,
    Teachers_Icon text,
    Teachers_Score text,
    Parent_Engagement_Icon text,
    Parent_Engagement_Score text,
    Parent_Environment_Icon text,
    Parent_Environment_Score text,
    AVERAGE_STUDENT_ATTENDANCE text,
    Rate_of_Misconducts__per_100_students_ real,
    Average_Teacher_Attendance text,
    Individualized_Education_Program_Compliance_Rate text,
    Pk_2_Literacy__ text,
    Pk_2_Math__ text,
    Gr3_5_Grade_Level_Math__ text,
    Gr3_5_Grade_Level_Read__ text,
    Gr3_5_Keep_Pace_Read__ text,
    Gr3_5_Keep_Pace_Math__ text,
    Gr6_8_Grade_Level_Math__ text,
    Gr6_8_Grade_Level_Read__ text,
    Gr6_8_Keep_Pace_Math_ text,
    Gr6_8_Keep_Pace_Read__ text,
    Gr_8_Explore_Math__ text,
    Gr_8_Explore_Read__ text,
    ISAT_Exceeding_Math__ real,
    ISAT_Exceeding_Reading__ real,
    ISAT_Value_Add_Math real,
    ISAT_Value_Add_Read real,
    ISAT_Value_Add_Color_Math text,
    ISAT_Value_Add_Color_Read text,
    Students_Taking__Algebra__ text,
    Students_Passing__Algebra__ text,
    "9th Grade EXPLORE (2009)" text,
    "9th Grade EXPLORE (2010)" text,
    "10th Grade PLAN (2009)" text,
    "10th Grade PLAN (2010)" text,
    Net_Change_EXPLORE_and_PLAN text,
    "11th Grade Average ACT (2011)" text,
    Net_Change_PLAN_and_ACT text,
    College_Eligibility__ text,
    Graduation_Rate__ text,
    College_Enrollment_Rate__ text,
    COLLEGE_ENROLLMENT integer,
    General_Services_Route integer,
    Freshman_on_Track_Rate__ text,
    X_COORDINATE integer,
    Y_COORDINATE integer,
    Latitude real,
    Longitude real,
    COMMUNITY_AREA_NAME text, 
    Ward integer,
    Police_District	integer,
    Location text
);"""
    
    # create tables
if conn is not None:
       # create  table
    create_table(conn, create_table_sql_1)
        # create  table
    create_table(conn, create_table_sql_2)
        # create  table
    create_table(conn, create_table_sql_3)
else:
    print("Error! cannot create the database connection.")

NameError: name 'conn' is not defined

unable to open database file
Error! cannot create the database connection.

In [26]:
import sqlite3
from sqlite3 import Error


def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        return conn
    except Error as e:
        print(e)

    return conn


def create_table(conn, create_table_sql):
    """ create a table from the create_table_sql statement
    :param conn: Connection object
    :param create_table_sql: a CREATE TABLE statement
    :return:
    """
    try:
        c = conn.cursor()
        c.execute(create_table_sql)
    except Error as e:
        print(e)


def main():
    database = r"C:\sqlite3\db_coursera\sqlite.db"
    
    create_table_sql_1 = """ CREATE TABLE IF NOT EXISTS ChicagoCensusData (
                                    COMMUNITY_AREA_NUMBER integer,
                                    COMMUNITY_AREA_NAME text,
                                    PERCENT_OF_HOUSING_CROWDED real,
                                    PERCENT_HOUSEHOLDS_BELOW_POVERTY real,
                                    PERCENT_AGED_16__UNEMPLOYED real,
                                    PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA real,
                                    PERCENT_AGED_UNDER_18_OR_OVER_64 real,
                                    PER_CAPITA_INCOME real,
                                    HARDSHIP_INDEX integer
                                );"""
        
    create_table_sql_2 = """ CREATE TABLE IF NOT EXISTS ChicagoCrimeData (
                                    COMMUNITY_AREA_NUMBER integer,
                                    ID integer,
                                    CASE_NUMBER text,
                                    DATE text,
                                    BLOCK text,
                                    IUCR text,
                                    PRIMARY_TYPE text,
                                    DESCRIPTION text,
                                    LOCATION_DESCRIPTION text,
                                    ARREST text,
                                    DOMESTIC text,
                                    BEAT integer,
                                    DISTRICT integer,
                                    WARD integer,
                                    FBICODE text,
                                    X_COORDINATE integer,
                                    Y_COORDINATE integer,
                                    YEAR integer,
                                    LATITUDE real,
                                    LONGITUDE real,
                                    LOCATION text
                                );"""

    create_table_sql_3 = """ CREATE TABLE IF NOT EXISTS ChicagoPublicSchools (
                                    COMMUNITY_AREA_NUMBER integer,
                                    School_ID integer,
                                    NAME_OF_SCHOOL text,
                                    "Elementary, Middle, or High School" text,
                                    Street_Address text,
                                    City text,
                                    State text,
                                    ZIP_Code integer,
                                    Phone_Number text,
                                    Link text,
                                    Network_Manager text,
                                    Collaborative_Name text,
                                    Adequate_Yearly_Progress_Made_ text,
                                    Track_Schedule text,
                                    CPS_Performance_Policy_Status text,
                                    CPS_Performance_Policy_Level text,
                                    HEALTHY_SCHOOL_CERTIFIED text,
                                    Safety_Icon text,
                                    SAFETY_SCORE text,
                                    Family_Involvement_Icon text,
                                    Family_Involvement_Score text,
                                    Environment_Icon text,
                                    Environment_Score integer,
                                    Instruction_Icon text,
                                    Instruction_Score text,
                                    Leaders_Icon text,
                                    Leaders_Score text,
                                    Teachers_Icon text,
                                    Teachers_Score text,
                                    Parent_Engagement_Icon text,
                                    Parent_Engagement_Score text,
                                    Parent_Environment_Icon text,
                                    Parent_Environment_Score text,
                                    AVERAGE_STUDENT_ATTENDANCE text,
                                    Rate_of_Misconducts__per_100_students_ real,
                                    Average_Teacher_Attendance text,
                                    Individualized_Education_Program_Compliance_Rate text,
                                    Pk_2_Literacy__ text,
                                    Pk_2_Math__ text,
                                    Gr3_5_Grade_Level_Math__ text,
                                    Gr3_5_Grade_Level_Read__ text,
                                    Gr3_5_Keep_Pace_Read__ text,
                                    Gr3_5_Keep_Pace_Math__ text,
                                    Gr6_8_Grade_Level_Math__ text,
                                    Gr6_8_Grade_Level_Read__ text,
                                    Gr6_8_Keep_Pace_Math_ text,
                                    Gr6_8_Keep_Pace_Read__ text,
                                    Gr_8_Explore_Math__ text,
                                    Gr_8_Explore_Read__ text,
                                    ISAT_Exceeding_Math__ real,
                                    ISAT_Exceeding_Reading__ real,
                                    ISAT_Value_Add_Math real,
                                    ISAT_Value_Add_Read real,
                                    ISAT_Value_Add_Color_Math text,
                                    ISAT_Value_Add_Color_Read text,
                                    Students_Taking__Algebra__ text,
                                    Students_Passing__Algebra__ text,
                                    "9th Grade EXPLORE (2009)" text,
                                    "9th Grade EXPLORE (2010)" text,
                                    "10th Grade PLAN (2009)" text,
                                    "10th Grade PLAN (2010)" text,
                                    Net_Change_EXPLORE_and_PLAN text,
                                    "11th Grade Average ACT (2011)" text,
                                    Net_Change_PLAN_and_ACT text,
                                    College_Eligibility__ text,
                                    Graduation_Rate__ text,
                                    College_Enrollment_Rate__ text,
                                    COLLEGE_ENROLLMENT integer,
                                    General_Services_Route integer,
                                    Freshman_on_Track_Rate__ text,
                                    X_COORDINATE integer,
                                    Y_COORDINATE integer,
                                    Latitude real,
                                    Longitude real,
                                    COMMUNITY_AREA_NAME text, 
                                    Ward integer,
                                    Police_District	integer,
                                    Location text
                                );"""

    # create a database connection
    conn = create_connection(database)

    # create tables
    if conn is not None:
        # create projects table
        create_table(conn, create_table_sql_1)

        # create tasks table
        create_table(conn, create_table_sql_2)
        
        # create tasks table
        create_table(conn, create_table_sql_3)
    else:
        print("Error! cannot create the database connection.")


if __name__ == '__main__':
    main()

# Insert Data in Sqlite3 tables

In [29]:
import sqlite3
from sqlite3 import Error

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
    except Error as e:
        print(e)

    return conn


def create_t1(conn, t1_file):
    """
    Create a new project into the projects table
    :param conn:
    :param project:
    :return: project id
    """
    sql = ''' INSERT INTO ChicagoCensusData(COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX)
              VALUES(?,?,?,?,?,?,?,?,?) '''
    cur = conn.cursor()
    rows = csv.reader(t1_file)
    cur.executemany(sql, rows)
    conn.commit()
    return cur.lastrowid

def create_t2(conn, t2_file):
    """
    Create a new task
    :param conn:
    :param task:
    :return:
    """

    sql = ''' INSERT INTO ChicagoCrimeData(ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,BEAT,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION)
              VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) '''
    cur = conn.cursor()
    rows = csv.reader(t2_file)
    cur.executemany(sql, rows)
    conn.commit()
    return cur.lastrowid

def create_t3(conn, t3_file):
    """
    Create a new task
    :param conn:
    :param task:
    :return:
    """

    sql = ''' INSERT INTO ChicagoPublicSchools(School_ID,NAME_OF_SCHOOL,"Elementary, Middle, or High School",Street_Address,City,State,ZIP_Code,Phone_Number,Link,Network_Manager,Collaborative_Name,Adequate_Yearly_Progress_Made_,Track_Schedule,CPS_Performance_Policy_Status,CPS_Performance_Policy_Level,HEALTHY_SCHOOL_CERTIFIED,Safety_Icon,SAFETY_SCORE,Family_Involvement_Icon,Family_Involvement_Score,Environment_Icon,Environment_Score,Instruction_Icon,Instruction_Score,Leaders_Icon,Leaders_Score,Teachers_Icon,Teachers_Score,Parent_Engagement_Icon,Parent_Engagement_Score,Parent_Environment_Icon,Parent_Environment_Score,AVERAGE_STUDENT_ATTENDANCE,Rate_of_Misconducts__per_100_students_,Average_Teacher_Attendance,Individualized_Education_Program_Compliance_Rate,Pk_2_Literacy__,Pk_2_Math__,Gr3_5_Grade_Level_Math__,Gr3_5_Grade_Level_Read__,Gr3_5_Keep_Pace_Read__,Gr3_5_Keep_Pace_Math__,Gr6_8_Grade_Level_Math__,Gr6_8_Grade_Level_Read__,Gr6_8_Keep_Pace_Math_,Gr6_8_Keep_Pace_Read__,Gr_8_Explore_Math__,Gr_8_Explore_Read__,ISAT_Exceeding_Math__,ISAT_Exceeding_Reading__,ISAT_Value_Add_Math,ISAT_Value_Add_Read,ISAT_Value_Add_Color_Math,ISAT_Value_Add_Color_Read,Students_Taking__Algebra__,Students_Passing__Algebra__,"9th Grade EXPLORE (2009)","9th Grade EXPLORE (2010)","10th Grade PLAN (2009)","10th Grade PLAN (2010)",Net_Change_EXPLORE_and_PLAN,"11th Grade Average ACT (2011)",Net_Change_PLAN_and_ACT,College_Eligibility__,Graduation_Rate__,College_Enrollment_Rate__,COLLEGE_ENROLLMENT,General_Services_Route,Freshman_on_Track_Rate__,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,Ward,Police_District,Location)
              VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) '''
    cur = conn.cursor()
    rows = csv.reader(t3_file)
    cur.executemany(sql, rows)
    conn.commit()
    return cur.lastrowid

def main():
    database = r"C:\sqlite3\db_coursera\sqlite.db"

    # create a database connection
    conn = create_connection(database)

    with conn:
        # create a new project
        t1_file = open("C:\sqlite3\db_coursera\ChicagoCensusData.csv")
        t1 = create_t1(conn, t1_file)

        # create a new project
        t2_file = open("C:\sqlite3\db_coursera\ChicagoCrimeData.csv")
        t2 = create_t2(conn, t2_file)

        # create a new project
        t3_file = open("C:\sqlite3\db_coursera\ChicagoPublicSchools.csv")
        t3 = create_t3(conn, t3_file)

if __name__ == '__main__':
    main()

In [35]:
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    cur.execute("SELECT * FROM ChicagoCrimeData")

    rows = cur.fetchall()

    for row in rows:
        print(row)

In [83]:
cur = conn.cursor()
cur.execute("select max(CrimeCount) from (SELECT COMMUNITY_AREA_NAME, count(*) as CrimeCount FROM ChicagoCensusData group by 1)")
rows = cur.fetchall()
for row in rows:
    print(row)

(3,)

In [37]:
    conn = create_connection(database)

In [72]:
cur = conn.cursor()
cur.execute("DELETE FROM ChicagoCensusData WHERE HARDSHIP_INDEX = ''  ")
rows = cur.fetchall()
for row in rows:
    print(row)